# Generated by Django 4.2.5 on 2023-09-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventage_row_1', models.TextField(verbose_name='Строка 1')),
                ('adventage_row_2', models.TextField(help_text='ТЕКСТ <span>текст</span>', verbose_name='Строка 2')),
                ('adventage_row_3', models.TextField(verbose_name='Строка 3')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='HeaderNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Навигационный элемент',
                'verbose_name_plural': 'Навигационные элементы',
            },
        ),
    ]
