# Generated by Django 4.2.5 on 2023-09-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventage',
            name='adventage_row_1',
            field=models.CharField(max_length=32, verbose_name='Строка 1'),
        ),
        migrations.AlterField(
            model_name='adventage',
            name='adventage_row_2',
            field=models.TextField(help_text='ТЕКСТ <sраn>текст<span>', max_length=32, verbose_name='Строка 2'),
        ),
        migrations.AlterField(
            model_name='adventage',
            name='adventage_row_3',
            field=models.TextField(max_length=32, verbose_name='Строка 3'),
        ),
    ]
